# Generated by Django 5.0.1 on 2024-02-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valentinemessage',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
