# Generated by Django 5.0.1 on 2024-02-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_valentinemessage_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valentinemessage',
            old_name='recipient',
            new_name='recipient_name',
        ),
    ]
