# Generated by Django 5.0.1 on 2024-02-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_recipient_valentinemessage_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valentinemessage',
            name='answer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
